name: dart2ast_engine
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  path: ^1.8.0
  antlr4: ^4.13.1
  equatable: ^2.0.5
  uuid: ^4.3.3
  indent: ^2.0.0
  protobuf: ^3.1.0

  collection: any
dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
